### PR TITLE
General English fixes and a few PHP compatibility changes--no functionality changes except one bug in the sample model

### PR DESCRIPTION
**Pull request by sunnywalker**
Removed end-of-file closing PHP tags where unnecessary;
Converted short tag <?= to long tags for better compatibility when those are turned off in the php.ini;
Fixed a syntax error in the sample.model.php

### CODE REVIEW

**Comment by minitech** [comment]
`<?=` is part of the code style, I think, and people should be using PHP 5.4 anyway, where it's not part of `short_tags` and rather always on.

**Comment by sunnywalker** [comment]
In pre-PHP 5.4, the `<?=` is also affected by the short_tags setting in the php.ini and the project docs currently state that while the project will be moving to 5.4, it's still compatible with 5.3. That and my host isn't on 5.4 so I had to change it for my own use. :)

**Comment by EliW** [comment]
Thank you for the first pull request sunnywalker!  I have to agree with minitech however.   Would you mind submitting another pull request that has all your excellent text/bug/etc changes, but without the <?= changes?

I'm personally a huge fan of using <?= -- and as stated, very soon (like, perhaps later today when I get time to make some code changes), Treb is going to require PHP 5.4 anyway, because of some extra features that are going to be required.   And that will make it moot.  (From the main branch's point anyway)

Thanks again!

**Comment by sunnywalker** [comment]
I've removed the short tags, but because my host doesn't support short tags, I can't vouch for the accuracy of the changes.

**Comment by EliW** [comment]
Thanks, I pulled it in!

**Pull request merged**
